server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tangtang?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.jiao.tangtang.mapper

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql